FROM node:22.19-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm i
#RUN npm ci

COPY . .
RUN npm run build


FROM nginx:alpine AS runner

COPY --from=builder /app/.next /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]